# Generated by Django 2.2.1 on 2019-07-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190703_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='website',
        ),
    ]
