# Generated by Django 2.2.2 on 2019-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firm_name',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(default='1', max_length=100),
        ),
    ]
