# Generated by Django 2.2.1 on 2019-07-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190708_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='product',
            new_name='wishlist',
        ),
    ]
